import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Provider from '@/context/Provider'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider>
    <html lang="en">
      <head>
        <title>Bogdan</title>
      </head>
      <body
        className={`${montserrat.className} w-screen h-screen px-5 bg-[#262626]`}
      >
        {children}
      </body>
    </html>

    </Provider>
  );
}
