import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Provider from "@/context/Provider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en">
        <head>
          <title>Bogdan</title>
        </head>
        <body
          className={`${montserrat.className} px-5 lg:px-32 xl:px-40 bg-[#262626] bg-no-repeat`}
        >
          {children}
        </body>
      </html>
    </Provider>
  );
}
